### ISSUE TITLE
SCI Spec ISO Standard Media Release

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/standards-wg#106]
The SCI Spec has been approved by the ISO and been published on the website: https://www.iso.org/standard/86612.html

**The announcement is to happen after the SWG merge v1.1 into the main branch on Thursday, April 11, 2024.**

For clarification: we can announce then that ISO has published v1.0 and the latest approved v1.1 is available.

NEXT STEPS

- [x] @NAMRATA-WOKE to [draft Media Release](https://docs.google.com/document/d/1BuH6fHeWqqI7_cy7l1mvmts_V_ZC9jpY0B5wunt07hg/edit?usp=sharing)
- [x] @Jenya-design to create graphic
- [x] @seanmcilroy29 to place PR on Thursday's agenda for review
- [x] @NAMRATA-WOKE to curate list of media contacts 
- [x] @NAMRATA-WOKE to draft pitch and reach out to select media April 11 - 16
- [x] @NAMRATA-WOKE to publish announcement on GSF April 16
- [x] @NAMRATA-WOKE to share stand-a-lone newsletter sharing the announcement
- [x] @NAMRATA-WOKE to notify all members April 17

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE  please check the graphic attached and [on Drive](https://drive.google.com/drive/folders/1PdBgR19qBBbgez5PIg9JqNzrL8D5NjRz?usp=sharing)
There are two size options:

Regular image for article size
![Image](https://github.com/Green-Software-Foundation/standards-wg/assets/69306070/2fa289a2-64b0-45f6-9c2a-372772290e65)

600px wide smaller image for Mailchimp etc
![Image](https://github.com/Green-Software-Foundation/standards-wg/assets/69306070/e4cd9ef0-3e9d-45f9-8ae1-f2077c525bd0)

Let me know if you need any adjustments
