### ISSUE TITLE
2022.09.22 - Agenda/Minutes

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#14]
## 2022.09.22 Minutes

Time 1630 (GMT) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Co-Chair – Abhishek Gupta (BCG)
- Co-Chair - Henry Richards (WattTime)
- Convener – Sean Mcilroy (Linux Foundation)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
WG agreed to record all [Meetings](https://docs.google.com/document/d/1WeRybJv8a8vunyRe9AawSqP0feVfe2PJ0KKiAGkI7kQ/edit). This meeting recording will be available until the next scheduled meeting

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.
> Sean requested for attending members to submit an issue to indicate their attendance

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call 
- [x] Approve agenda
> Sean reviews the agenda - Tammy motions to Approve - agenda approved
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/standards_wg/blob/main/Agenda_Minutes/2022.09.15.Minutes.md)
> Tammy motions to approve the previous meeting minutes - No objections - minutes approved

## [Software Carbon Intensity (SCI)](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md)

- [x] [SCI PRs](https://github.com/Green-Software-Foundation/software_carbon_intensity/pulls)
  - [x] https://github.com/Green-Software-Foundation/software_carbon_intensity/pull/313
> WG agreed and merged
  - [x] https://github.com/Green-Software-Foundation/software_carbon_intensity/pull/315
> WG agreed close without merging

- [x] [SCI Issues](https://github.com/Green-Software-Foundation/software_carbon_intensity/issues)
  - [x] https://github.com/Green-Software-Foundation/sci-faq/issues/2
  - [x] https://github.com/Green-Software-Foundation/sci-faq/issues/1
  - [x] https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/311
  - [x] https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/312
  - [x] https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/314
  - [x] https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/316

- [x] Motion to approve SCI v1.0
> To be discussed at the next meeting

- [x] Next steps
> Sean proposed that once the WG agree the SCI, it should be submitted to become an ISO specification
WG Agreed for Sean to submit this to ISO

## [Standards WG Webpage](https://standards.greensoftware.foundation) context development

- [x] [Creation of supporting pages for docusaurus](https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/294)
  - [x] [FAQ](https://github.com/Green-Software-Foundation/software_carbon_intensity/issues?q=is%3Aopen+is%3Aissue+label%3AFAQ) submissions / suggestions
   - For FAQ submissions - [click here](https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/new/choose)
    - [x] Member suggestions for content to be added

## Case Study Updates

- [x] Accenture (Navveen) --> Update expected Mid to late Sept
- [x] Gadhu NTT --> Update expected Mid Sept
- [x] Henry - University of Washington 
- [x] Pindy - UBS --> Update expected Mid Sept
- [x] Wendy - AVEVA --> Update expected Mid Sept
- [x] Tammy - MSFT/Dow - Working on SCI based case study

## AOB, Q&A 
> Nothing added

## Next Meeting

- [x] 29th Sept
> Agreed

## Adjourn 
Tammy motions to approved Meeting closed @ 1734

**Comment by atg-abhishek** [comment]
Attended

**Comment by seanmcilroy29** [comment]
attended

**Comment by navveenb** [comment]
Attended

**Comment by tmcclell** [comment]
Attended

**Comment by Henry-WattTime** [comment]
attended

**Comment by kapokasa** [comment]
Attended

**Comment by kreyesra** [comment]
attended

**Comment by deepak-sharma14** [comment]
attended

**Comment by PindyBhullar** [comment]
attended

**Comment by Sealjay** [comment]
attended (forgot to comment)

**Comment by chrisxie-fw** [comment]
attended.

**Comment by benlogan** [comment]
Attended

**Comment by navveenb** [comment]
Attended

**Comment by kreyesra** [comment]
Attended

**Comment by chrisxie-fw** [comment]
attended.
