### ISSUE TITLE
[Case Study] UBS Data updates

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#20]

**Comment by Henry-WattTime** [comment]
Update: Might not be able to test SCI fully. Running SCI in application in investment bank. Awaiting data. Pushing asset management/IT to also measure. Ready in new year, separated over the next couple months. Verbal update, written update to follow.

**Comment by Henry-WattTime** [comment]
Pindy: mobilizing a working group to do calculations and writeup (already drafted)

**Comment by PindyBhullar** [comment]
We have a very high level result for an application. I can present to this group our findings, and our gaps on Thursday 30th March.

**Comment by PindyBhullar** [comment]
Apologies i have been delayed in completing the case study, i will try to wrap it up in the coming weeks.

**Comment by PindyBhullar** [comment]
Presented the two case studies on 13th July 2023. The next task is to submit a paper on the process that was followed to calculate SCI.

**Comment by seanmcilroy29** [comment]
@PindyBhullar - Once you've completed the paper, could you please forward it to me? I'd like to draft an article for the Working Group to review before we publish it.
