### ISSUE TITLE
[Case Study] [NTT DATA] On-Premise Web system

### ISSUE THREAD

**Issue by YaSuenag** [Green-Software-Foundation/standards-wg#36]
# On-Premise Web system

## Overview

* We calculated SCI value for a web system following 3-tier architecture.
* Calculating SCI value through this case study involves measuring the behavior of components and their results based on scenarios.
* We deployed TPC-W implementation proposed by [Transaction Processing Performance Council](https://www.tpc.org/) as a workload.
    * TPC-W is designed for measuring performance and cost for performance in an environment where online transaction processing (OLTP) is set up for e-commerce.
* In areas where it is difficult to measure, it is estimated by publication from trusted institutions.
* We assume life span of this system is 4 years, then `M` is divided by 35040 [hours] (4 [years] * 365 [days] * 24 [hours])

## Architecture for the system under consideration

![architecture](https://user-images.githubusercontent.com/7421132/206328519-542677ef-6e8b-495e-b1d9-a2bdd5c5b02e.png)

### Technical details of the components in the architecture

* The architecture is configured by several network switches, LB/Web servers, AP servers, and DB servers.
    * They have redundant components.
    * They are located at data center which PUE assumes 1.5 .
* The database server is based on PostgreSQL with [PG-REX](https://wiki.clusterlabs.org/wiki/PgSQL_Replicated_Cluster)
* Each servers has bonding network interface with active-backup.
    * Layer 2 network switch `#1` and `#3` are connected from active interface.
    * Layer 2 network switch `#2` and `#4` are connected from backup interface.
* In LB/Web servers, `#1` is active, `#2` is backup server.
* In database server, `#1` is primary, `#2` is secondary server.

#### Included

* Load Balacners/Web servers (piggyback)
* Application servers
* Database servers
* Layer 3 network switch (L3 switch)
* Layer 2 network switches (L2 switch)

#### Excluded

* Web clients (desktop, laptop, mobile, and so on)

### (Scale) Functional unit 

Defines `R` is 1 [operation].

Result of TPC-W benchmark is Web Interactions Per Second (WIPS), which is the number of responses (throughput) from the web server per second. In this case study, we got 10564.65 [WIPS].

1 [operation] is defined as 10 [WI] (assumes 10 interactions happen in an operation by human).

As we wrote above, we defined 1 [operation] as 10 [WI], so we need to divide SCI with "scale factor" to align to `R` (1 [operation]).

```
[scale factor] = [WIPS] / [WI per operations] * [hour in seconds]
               = 10564.65 / 10 * 3600
               = 3803274
```
##### Energy (`E`)

Estimates from [data sheet of Cisco Catalyst 9300 Series](https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-9300-series-switches/nb-06-cat9300-ser-data-sheet-cte-en.html) and from `5 minute input rate`/`5 minute output rate` on Cisco IOS.

From Table.22 of data sheet, our network switch consumes 92.5 [W] in full port 100% traffic. We use this value as base line.

`5 minute input rate` and `5 minute output rate` from `show interfaces` command on Cisco IOS shows mean an approximation of traffic per second during a given 5-minute period. We collect these values several times, and calculate median of sum of them because they are connected with full duplex. Note that we should collect values from ports which we used only.

```
>show interfaces Gi1/0/13
GigabitEthernet1/0/13 is up, line protocol is up (connected)

 ~snip~

  Full-duplex, 1000Mb/s, media type is 10/100/1000BaseTX

 ~snip~

  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 2000 bits/sec, 2 packets/sec

 ~snip~
```

We can estimate energy consumption with following:

```
[Max power consumption per port] = [value from ATIS] / [kW] * [hour in seconds] / [number of ports]
                                 = 92.5 / 1000 * 3600 / 24
                                 = 13.8 [kWh/port]
[E per port] = [Max power consumption per port] * median([5 minute input rate] + [5 minute output rate]) / 2 (full duplex) / [link speed (Gbps)]
             = 13.8 * median([5 minute input rate] + [5 minute output rate]) / 2 / 1000000000

E = sum([E per port]) * [PUE]
  = sum([E per port]) * 1.5
```

##### Carbon Intensity (`I`)

* We use regional yearly averages.
* The region the application was run in was Yokohama, Japan.
* According to [publication from TEPCO](https://www.tepco.co.jp/ep/company/warming/) (electric power company in Japan: Japanese), carbon intensity in 2021 is 0.457 [kgCO2/kWh] = 457 [gCO2/kWh]

##### Embodied Carbon (`M`)

This was on-premise system, and it was occupied by this workload. So we can use PCF from manufacturers straightly.

However Cisco has not published PCF of Catalyst 9300 series (Nov, 2022 at least), so we use [emission factor database from Ministry of the Environment in Japan](https://www.env.go.jp/earth/ondanka/supply_chain/gvc/estimate_tool.html) (ver. 3.2, in Japanese).

According this database, network switch is categorized to “computer accessories”, and one switch's PCF is 0.251 [tCO2eq] in quantity-based emissions intensity (No.239, code 333103). Thus we can estimate embodied carbon in mesurement duration with following:

```
M = 0.251 [tCO2eq] / [4 years in hour]
  = 251000 [gCO2eq] / 35040 [hours]
  = 7.16 [gCO2eq/hour]
```

##### Energy (`E`)

As well as Catalyst 9300, estimates from [data sheet of Cisco Catalyst 1000 Series](https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-1000-series-switches/nb-06-cat1k-ser-switch-ds-cte-en.html) and from `5 minute input rate`/`5 minute output rate` on Cisco IOS.

From Table 2 of data sheet, our network switch consumes 22.8 [W] in 1Gbps 100% traffic. We will use this value as base line.

We can estimate energy consumption with following:

```
[Max power consumption per port] = [value from data sheet] / [kW] * [hour in seconds] / [number of ports]
                                 = 22.8 / 1000 * 3600 / 24
                                 = 3.4 [kWh/port]
[E per port] = [Max power consumption per port] * median([5 minute input rate] + [5 minute output rate]) / 2 (full duplex) / [link speed (Gbps)]
             = 3.4 * median([5 minute input rate] + [5 minute output rate]) / 2 / 1000000000

E = sum([E per port]) * [PUE]
  = sum([E per port]) * 1.5
```

##### Carbon Intensity (`I`)

This network switches are located at same datacenter with L3 switch, so we use 457 [gCO2/kWh] as well as it.

##### Embodied Carbon (`M`)

As well as L3 switch, we use emission factor database from Ministry of the Environment in Japan. So `M` is 7.16 [gCO2eq/hour].

##### Energy (`E`)

These servers support IPMI (Intelligent Platform Management Interface), so we can use [ipmitool](https://github.com/ipmitool/ipmitool).

```bash
$ ipmitool -I lanplus -H [host] -U [username] -P [passphrase] dcmi power reading

    Instantaneous power reading:                   176 Watts
    Minimum during sampling period:                  1 Watts
    Maximum during sampling period:               6560 Watts
    Average power reading over sample period:      113 Watts
    IPMI timestamp:                           Thu Dec  1 11:41:20 2022
    Sampling period:                          00000001 Seconds.
    Power reading state is:                   activated
```

The command is executed from remote host several times. We use average of `Instantaneous power reading` as power consumption.

We convert this value (Watt) to energy (kWh) with following formula:

```
E = [average of Instantaneous power reading] / [kW] * [hour in seconds] * [PUE]
  = [average of Instantaneous power reading] / 1000 * 3600 * 1.5
```

##### Carbon Intensity (`I`)

These servers are located at same datacenter with network switches, so we use 457 [gCO2/kWh] as well as network switches.

##### Embodied Carbon (`M`)

In this system, we use HPE DL360 Gen10. According to [data sheet from HPE](https://www.hpe.com/psnow/doc/a50002430enw), PCF is 6270 [kgCO2eq]. Thus we can estimate embodied carbon in mesurement duration with following:

```
M = 6270 [kgCO2eq] / [4 years in hour]
  = 6270000 [gCO2eq] / 35040 [hours]
  = 178.93 [gCO2eq/hour]
```

#### L3 switch ((1) in figure of architecture)

```
[Max power consumption per port] = [value from ATIS] / [kW] * [hour in seconds] / [number of ports]
                                 = 92.5 / 1000 * 3600 / 24
                                 = 13.8 [kWh/port]
[E per port] = [Max power consumption per port] * median([5 minute input rate] + [5 minute output rate]) / 2 (full duplex) / [link speed (Gbps)]
             = 13.8 * median([5 minute input rate] + [5 minute output rate]) / 2 / 1000000000

E = sum([E per port]) * [PUE]
  = 11.89 [kWh] * 1.5
  = 17.83 [kWh]

SCI = ((E * I) + M) / [scale factor] per R
    = ((17.83 [kWh] * 457 [gCO2/kWh]) + 7.16 [gCO2eq/hour]) / 3803274 per R
    = 0.00 [gCO2eq] per R
```

#### L2 switch ((2) in figure of architecture)

```
[Max power consumption per port] = [value from data sheet] / [kW] * [hour in seconds] / [number of ports]
                                 = 22.8 / 1000 * 3600 / 24
                                 = 3.4 [kWh/port]
[E per port] = [Max power consumption per port] * median([5 minute input rate] + [5 minute output rate]) / 2 (full duplex) / [link speed (Gbps)]
             = 3.4 * median([5 minute input rate] + [5 minute output rate]) / 2 / 1000000000

E = sum([E per port]) * [PUE]
  = sum([E per port]) * 1.5
```

##### L2 `#1`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((2.90 [kWh] * 457 [gCO2/kWh]) + 7.16 [gCO2eq/hour]) / 3803274 per R
    = 0.00 [gCO2eq] per R
```

##### L2 `#2`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((0.00 [kWh] * 457 [gCO2/kWh]) + 7.16 [gCO2eq/hour]) / 3803274 per R
    = 0.00 [gCO2eq] per R
```

##### L2 `#3`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((3.42 [kWh] * 457 [gCO2/kWh]) + 7.16 [gCO2eq/hour]) / 3803274 per R
    = 0.00 [gCO2eq] per R
```

##### L2 `#4`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((0.00 [kWh] * 457 [gCO2/kWh]) + 7.16 [gCO2eq/hour]) / 3803274 per R
    = 0.00 [gCO2eq] per R
```

#### Physical severs ((3) - (5) in figure of architecture)

```
E = [average of Instantaneous power reading] / [kW] * [hour in seconds] * [PUE]
  = [average of Instantaneous power reading] / 1000 * 3600 * 1.5
```

##### LB/Web server `#1`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((503.28 [kWh] * 457 [gCO2/kWh]) + 178.93 [gCO2eq/hour]) / 3803274 per R
    = 0.06 [gCO2eq] per R
```

##### LB/Web server `#2`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((419.04 [kWh] * 457 [gCO2/kWh]) + 178.93 [gCO2eq/hour]) / 3803274 per R
    = 0.05 [gCO2eq] per R
```

##### AP server `#1`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((538.92 [kWh] * 457 [gCO2/kWh]) + 178.93 [gCO2eq/hour]) / 3803274 per R
    = 0.06 [gCO2eq] per R
```

##### AP server `#2`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((530.92 [kWh] * 457 [gCO2/kWh]) + 178.93 [gCO2eq/hour]) / 3803274 per R
    = 0.06 [gCO2eq] per R
```

##### DB server `#1`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((930.42 [kWh] * 457 [gCO2/kWh]) + 178.93 [gCO2eq/hour]) / 3803274 per R
    = 0.11 [gCO2eq] per R
```

##### DB server `#2`

```
SCI = ((E * I) + M) / [scale factor] per R
    = ((696.06 [kWh] * 457 [gCO2/kWh]) + 178.93 [gCO2eq/hour]) / 3803274 per R
    = 0.08 [gCO2eq] per R
```

### SCI Total

The total SCI for the whole system.

```
SCI = [SCI of L3 switch] + sum([SCI of L2 switches]) + sum([SCI of physical servers])
    = 0.00 + 0.00 + 0.42
    = 0.42 [gCO2eq per R (1 operation)]
```

**Comment by srini1978** [comment]
Thanks @GadhuNTTDATA  for sharing this case study. 

A couple of thoughts.

1. Case study has chosen the functional unit R as WIPS. Can this be the scaling factor for all the components of the software boundary - L3 and L2 switches, AP servers and DB servers. As per our definition of functional unit in the SCI specs, "A consistent choice of R across all the components in the software boundary shall be used" .  Hence wondering if the chosen R in this case study is more a scaling factor for the Web server

For e. g when we define a functional unit as "Users" then we mean that the entire software components will scale by this functional unit and when we make improvements by either reducing hardware or making it more energy efficient, this functional unit wiill come into play and say that in 

Iteration 1: SCI score of the app is 100 kgCo2eq per 5000 users
Iteration 2 : SCI score of the app is now 80kgCo2eq per 5000 users

2. My understanding of functional unit is that we say SCI per R.  For example in the above output i have quoted we cannot say that SCI score = 100/5000 = 0.02 kgC2eq per user. This is because SCI score has no linear relationship with number of users and hence we may not be able to divide final SCI score by "compound functional unit". @jawache  @atg-abhishek  - thoughts ?

3. Another point is : if we reduce the hardware specs used for the architecture, based on the current thinking in the case study the WIPS will technically decrease. SCI will decrease as well  . I am not very sure whether this outcome is expected because based on the current thinking of the optimization opportunities we either manipulate E(energy aware), I (carbon aware) or M (hardware efficiency) to reduce the SCI score. We have never really covered how to reduce SCI score by manoevering R and we have always used R as a reference scaling factor. 

Thoughts ?  


FYI @Henry-WattTime  @atg-abhishek

**Comment by YaSuenag** [comment]
Thanks @srini1978 for your comment.

> Case study has chosen the functional unit R as WIPS. Can this be the scaling factor for all the components of the software boundary - L3 and L2 switches, AP servers and DB servers. As per our definition of functional unit in the SCI specs, "A consistent choice of R across all the components in the software boundary shall be used" . Hence wondering if the chosen R in this case study is more a scaling factor for the Web server

WIPS means "Web Interactions per seconds", so it is affected from all components includes network switches and web server.

> We have never really covered how to reduce SCI score by manoevering R and we have always used R as a reference scaling factor.

I've updated case study to clarify each words. We use "Web Interaction [WI]" for `R`, we are proposing to evaluate carbon intensity via this value - `R` is fixed even if WIPS is changed.

**Comment by Henry-WattTime** [comment]
Quick question about units - 
`[Max power consumption per port] = [value from data sheet] / [kW] * [hour in seconds] / [number of ports]
                                 = 22.8 / 1000 * 3600 / 24
                                 = 3.4 [kWh/port]`

Wouldn't this results in units of KWs/port? Should the 3600 seconds be dropped?
`[Max power consumption per port] = [value from data sheet (W)] / [1000 (W/kW)] * [hour in seconds (3600s)] / [number of ports (#)]'
Am I missing something here?

**Comment by YaSuenag** [comment]
@Henry-WattTime 

https://www.rapidtables.com/electric/watt.html#w%20to%20j
1 [J] = 1 [W] * 1 [sec]

https://www.rapidtables.com/convert/energy/kWh_to_Joule.html#how
1 [kWh] = 3600000 [J] = 1 [J] * 3600 [sec] * 1000 [k]

So this formula is correct, and we should keep 3600 in it.

**Comment by Henry-WattTime** [comment]
Are the units of the power consumption in jules? I would have expected Watts. I think I need to see the formula with the units written out for it to make sense to me.

**Comment by YaSuenag** [comment]
SCI spec requires kWh for `E`, not Watts. So I think we need to be aware of energy consumption like jules.
https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/main/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#energy

However we can only measure power consumption [W] here, so we need to convert it to [kWh]. This case study proposes it.

I think formula in below can be ease to understand. What do you think?

```
[Max power consumption per port in kW] =  [value from data sheet [W]] / 1000 [k] / [number of ports]

E is expected in kWh, so we need to convert kW to kWh in below:

[J] = [W] * 1 [sec]
[kWh] = [J] * 3600 [sec] * 1000 [k]
      = [W] * 3600 [sec] * 1000 [k]

So we use the result of the formula in below:

[Max energy consumption per port in kWh] = [Max power consumption per port in kW] * 3600 [sec]
```

**Comment by Henry-WattTime** [comment]
Ah, in that case I think you wouldn't need to multiply by 3600 to get kWh as that would results in kWs. If you have a device that consumes 6 kW of power instantaneously, then if you use it for an hour, it will consume 6 kWh  of energy (6 kW * 1hr). We never need to drop into joules if the units of power consumption are in watts (or kilowatts), we just need to multiply by the duration of use in hours. Does that make sense?

**Comment by YaSuenag** [comment]
Thank you all for your comments! I've updated our case study and have moved to it to SCI repo https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/342

So I close this issue.

I'd like to continue to discuss about it in new place.
