### ISSUE TITLE
Using software emission calculation data for organisational decision making during the development and use of technology applications.

### ISSUE THREAD

**Issue by PindyBhullar** [Green-Software-Foundation/standards-wg#77]
**Working title:** Using software emission calculation data for organisational decision making during the development and use of technology applications.

**Related issues:** This project proposition is a continuation of @tmcclell's "answering the so-what query" discussion.
https://github.com/Green-Software-Foundation/oc/discussions/18

**Tagline:** "The adoption and usage of software emission data"

**Abstract:** The creation of the SCI facilitates the calculation of software carbon emissions. In addition, there is an initiative that focuses on cloud calculations in real time. Over time, additional calculation methodologies and tools may be developed, but the actual implementation necessitates organisational changes that must be addressed. This project will result in the creation of a framework for decision-making during the development and implementation of technology applications by incorporating all available methodologies and instruments.

The initiative will concentrate on the broader organisation's adoption of calculations and the measures organisations must take to ensure that measuring CO2 is an integral part of application development.
I propose that we use the TCFD framework as a basis for integrating organisational areas that facilitate the flow of CO2 data into strategic and executive-level decisions.

The outputs from working groups and sub-working groups creating methodologies and tools will be used to develop a framework for organisations to use and employ in order to make actual distinctions. This will include the principles of shared data, the formulation of OKRs and KPIs, the modification of behaviours, and their incorporation into organisational change processes and practices.

**Quote:** "Change before you have to." - Jack Welch

**Audience:** This solution's intended audience consists of technology architects, devops lead engineers, programmers and project managers, product managers, business managers, and business executives. This audience receives limited and, in some instances, no data at all (this view is based on my PhD research). This topic can be discussed at numerous conferences, including technology, programme management, ESG, and supply chain conferences.
 
**ToC:** By the end of 2024, this initiative will enhance the adoption of various GSF tools and methodologies.

**Governance:** The governance of this proposal spans a number of WGs, and I would like the Steering Committee to provide guidance.

**Problems to resolve:**

- Once the baseline for software's CO2 emissions has been established, how do organisations make informed decisions?
- How do organisations establish goals using software data on carbon dioxide emissions?
- What critical behavioural changes and external influences are required for the devops community to adopt green engineering practices?
- How can procurement teams use software emissions data to ensure that contracts with ITO and BPO vendors meet organisational objectives?
- What are the most important judgements and options during the development of a business case for software solutions?
- How do costs, business growth, and CO2 targets interact within a business?
- How can organisations establish meaningful OKRs and KPIs to reduce software-related CO2 emissions?
- What challenges do organisations face? Is there an opportunity for industry and tech innovators to assist in resolving these issues?
- What effect do the emissions of carbon dioxide have on regulatory disclosures?
- How long will it take to implement granular reporting?

As carbon emissions from software do not fall solely under the responsibility of technology departments or functions, the initiative aims to integrate the methodologies and tools across the entire organisation.

**Solution:** The solution would be a framework incorporating a decision tree strategy. It would also reveal where voids exist, providing ideas for future initiatives.

**Closure:** For the project to be successful, GSF organisations must test the framework throughout its development and numerous iterations. The SCI is an excellent example of a system whose implementation within organisations resulted in a continuous feedback cycle.

**Comment by Henry-WattTime** [comment]
WG understanding:
This helps organizations with goal setting and organizational strategy. 
In contrast to the tools like the SCI, Impact engine which may be used by organizations in developing tools.

UBI: calculation was an early test at calculating score for small sector of business, long term figure out how to roll out to entire business. Tool measures as well as recommends actions/strategies to reduce emissions. Menu of options, aware of strategy. 

How do we help other organizations on that same journey from small pilot to larger deployment across the organization.

**Comment by nttDamien** [comment]
I'm still rather unfamiliar with the domain, and wondering if it would make more sense to use CSRD framework as a basis ?
As this legal framework (extending TCFD) creates reporting obligations, that might be more appealing to organisations (50k+ in Europe) in order to meet their reporting obligations.

**Comment by PindyBhullar** [comment]
Thanks for your comments @Henry-WattTime 
Your points are accurate.

**Comment by PindyBhullar** [comment]
@nttDamien using CSRD makes sense. The framework provides a structure to ground the analysis and thinking. 
Reporting regulations on ESG are constantly changing, so we should try to be agnostic as possible. This project is uncovering data, providing tools to make the sustainable (energy and carbon decisions). The outcomes from this process may need to flex depending on the jurisdictions of the regulations.

**Comment by navveenb** [comment]
@PindyBhullar, Creating a decision tree for embedding carbon reduction as a first-class citizen is a good strategy. All organizations go through similar challenges that you have listed. Having a standardized approach would be helpful.

**Comment by seanmcilroy29** [comment]
Project approved
