### ISSUE TITLE
The dev branch of SCI specification gives 404 error

### ISSUE THREAD

**Issue by navveenb** [Green-Software-Foundation/standards-wg#87]
@seanmcilroy29 The dev branch is giving a 404 error. Pls, check.
https://github.com/Green-Software-Foundation/sci/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md

**Comment by Henry-WattTime** [comment]
It moved I think when Asim cleaned things up? try this link? https://github.com/Green-Software-Foundation/sci/blob/dev/SPEC.md

**Comment by seanmcilroy29** [comment]
@navveenb - The Dev branch folders and the naming were updated for consistency. Any previously bookmarked links would now generate a 404 error. 

The link to the dev branch SCI is https://github.com/Green-Software-Foundation/sci/blob/dev/SPEC.md

Are we ok to close this issue?

**Comment by navveenb** [comment]
Yes, we can. The website references need to point to this dev branch. One of the references I came from is - https://github.com/Green-Software-Foundation/sci/tree/dev, which points to the 404 link. Is there a way to auto-redirect the old link to the new one.
